global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # External Labels
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
